export const GET_CONCERTS_SUCCESS = 'GET_CONCERTS_SUCCESS';
export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';
export const GET_SPOTIFY_ARTISTS_SUCCESS = 'GET_SPOTIFY_ARTISTS_SUCCESS';
export const GET_TRACK_SUCCESS = 'GET_TRACK_SUCCESS';