export const GET_CONCERTS_SUCCESS = 'GET_CONCERTS_SUCCESS';
export const SET_SELECTED_CONCERT = 'SET_SELECTED_CONCERT';
export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';
export const GET_SPOTIFY_ARTISTS_SUCCESS = 'GET_SPOTIFY_ARTISTS_SUCCESS';
export const GET_TRACK_SUCCESS = 'GET_TRACK_SUCCESS';
export const EMPTY_TRACKS = 'EMPTY_TRACKS';
export const SAVE_PLAYLIST_SUCCESS = 'SAVE_PLAYLIST_SUCCESS';